import json

nb_path = r"d:\Học máy và ứng dụng\Machine-Learning\Học máy\bai01\01. Linear_Regression\Linear_Regression.ipynb"

with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    cid = cell.get("id", "")
    
    # 1. Cập nhật import ở cell đầu tiên (lr-cell-01)
    if cid == "lr-cell-01":
        new_source = []
        for line in cell["source"]:
            if "from sklearn.linear_model import LinearRegression, Ridge, Lasso" in line:
                new_source.append("from sklearn.linear_model import LinearRegression, Ridge, Lasso, HuberRegressor\n")
            else:
                new_source.append(line)
        cell["source"] = new_source

    # 2. Cập nhật cell Bài 1 (lr-bt1-code)
    elif cid == "lr-bt1-code":
        cell["source"] = [
            "import numpy as np\n",
            "from sklearn.datasets import fetch_california_housing\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.linear_model import LinearRegression\n",
            "from sklearn.metrics import mean_squared_error, r2_score\n",
            "\n",
            "# 1. Định nghĩa class MyLinearRegression\n",
            "class MyLinearRegression:\n",
            "    def __init__(self):\n",
            "        self.w = None       # Trọng số cho các features\n",
            "        self.b = None       # Hệ số chặn (intercept / bias)\n",
            "        self.theta = None   # Vector [b, w_1, ..., w_n]\n",
            "        \n",
            "    def fit(self, X, y):\n",
            "        X = np.asarray(X, dtype=np.float64)\n",
            "        y = np.asarray(y, dtype=np.float64)\n",
            "        N = X.shape[0]\n",
            "        # Thêm cột 1 vào đầu ma trận cho hệ số bias b\n",
            "        X_b = np.column_stack([np.ones(N), X])\n",
            "        # Công thức nghiệm đóng Normal Equation: theta = (X_b^T X_b)^(-1) X_b^T y\n",
            "        # Dùng pinv để đảm bảo luôn nghịch đảo ổn định số học\n",
            "        self.theta = np.linalg.pinv(X_b.T @ X_b) @ X_b.T @ y\n",
            "        self.b = float(self.theta[0])\n",
            "        self.w = np.array(self.theta[1:], dtype=np.float64)\n",
            "        return self\n",
            "        \n",
            "    def predict(self, X):\n",
            "        X = np.asarray(X, dtype=np.float64)\n",
            "        return X @ self.w + self.b\n",
            "\n",
            "# 2. Kiểm thử trên tập dữ liệu California Housing\n",
            "housing = fetch_california_housing()\n",
            "X_raw, y_raw = housing.data, housing.target\n",
            "X_tr, X_te, y_tr, y_te = train_test_split(X_raw, y_raw, test_size=0.2, random_state=42)\n",
            "\n",
            "scaler = StandardScaler()\n",
            "X_tr_s = scaler.fit_transform(X_tr)\n",
            "X_te_s = scaler.transform(X_te)\n",
            "\n",
            "# Fit mô hình tự viết và mô hình sklearn\n",
            "my_lr = MyLinearRegression().fit(X_tr_s, y_tr)\n",
            "sk_lr = LinearRegression().fit(X_tr_s, y_tr)\n",
            "\n",
            "# Dự đoán và tính toán các chỉ số\n",
            "my_pred = my_lr.predict(X_te_s)\n",
            "sk_pred = sk_lr.predict(X_te_s)\n",
            "\n",
            "print(f\"[So sánh kết quả trên tập kiểm tra (Test Set)]:\")\n",
            "print(f\"MyLinearRegression:   R² = {r2_score(y_te, my_pred):.6f}, RMSE = {np.sqrt(mean_squared_error(y_te, my_pred)):.6f}\")\n",
            "print(f\"sklearn.LinearReg:   R² = {r2_score(y_te, sk_pred):.6f}, RMSE = {np.sqrt(mean_squared_error(y_te, sk_pred)):.6f}\")\n",
            "print(f\"Chênh lệch R²:        {abs(r2_score(y_te, my_pred) - r2_score(y_te, sk_pred)):.2e}\")\n",
            "print(f\"Chênh lệch bias b:    {abs(my_lr.b - sk_lr.intercept_):.2e}\")\n",
            "print(f\"Chênh lệch max w:     {np.max(np.abs(my_lr.w - sk_lr.coef_)):.2e}\")\n",
            "print(\"=> Nhận xét: Kết quả của MyLinearRegression hoàn toàn trùng khớp với sklearn!\")\n"
        ]

    # 3. Cập nhật cell Bài 2 (lr-bt2-code)
    elif cid == "lr-bt2-code":
        cell["source"] = [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.linear_model import LinearRegression\n",
            "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
            "\n",
            "np.random.seed(42)\n",
            "N_houses = 200\n",
            "# Diện tích từ 30m2 đến 200m2\n",
            "area = np.random.uniform(30, 200, N_houses)\n",
            "# Giá = 50 + 30 * area + nhiễu Gauss N(0, 300^2) (đơn vị: triệu đồng)\n",
            "noise = np.random.normal(0, 300, N_houses)\n",
            "price = 50 + 30 * area + noise\n",
            "\n",
            "# Huấn luyện Linear Regression\n",
            "lr_house = LinearRegression()\n",
            "lr_house.fit(area.reshape(-1, 1), price)\n",
            "price_pred = lr_house.predict(area.reshape(-1, 1))\n",
            "\n",
            "rmse_house = np.sqrt(mean_squared_error(price, price_pred))\n",
            "mae_house = mean_absolute_error(price, price_pred)\n",
            "r2_house = r2_score(price, price_pred)\n",
            "\n",
            "print(f\"Hàm thật gốc:      Giá = 30 * area + 50\")\n",
            "print(f\"Hồi quy học được:  Giá = {lr_house.coef_[0]:.2f} * area + {lr_house.intercept_:.2f}\")\n",
            "print(f\"Báo cáo chỉ số:\")\n",
            "print(f\"  - RMSE : {rmse_house:.2f} triệu đồng\")\n",
            "print(f\"  - MAE  : {mae_house:.2f} triệu đồng\")\n",
            "print(f\"  - R²   : {r2_house:.4f}\")\n",
            "\n",
            "# Vẽ scatter + đường hồi quy\n",
            "plt.figure(figsize=(8, 4.5))\n",
            "x_grid = np.linspace(30, 200, 300).reshape(-1, 1)\n",
            "plt.scatter(area, price, alpha=0.6, color='royalblue', label='Dữ liệu 200 căn nhà')\n",
            "plt.plot(x_grid, 50 + 30 * x_grid, 'g--', lw=2, label='Đường thật: y = 30x + 50')\n",
            "plt.plot(x_grid, lr_house.predict(x_grid), 'r-', lw=2.5, label=f'Đường hồi quy: y = {lr_house.coef_[0]:.2f}x + {lr_house.intercept_:.2f}')\n",
            "plt.xlabel('Diện tích (m²)')\n",
            "plt.ylabel('Giá nhà (triệu đồng)')\n",
            "plt.title(f'Bài tập 2: Dự đoán giá nhà theo diện tích (RMSE = {rmse_house:.2f} triệu, R² = {r2_house:.4f})')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.show()\n"
        ]

    # 4. Cập nhật cell Bài 3 (lr-bt3-code) -> SỬA LỖI HuberRegressor
    elif cid == "lr-bt3-code":
        cell["source"] = [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.linear_model import LinearRegression, HuberRegressor\n",
            "\n",
            "np.random.seed(42)\n",
            "N3 = 100\n",
            "x3 = np.linspace(0, 10, N3)\n",
            "y3 = 3 * x3 + 5 + np.random.randn(N3) * 1.5\n",
            "\n",
            "# Thêm 5 outlier mạnh (y = 100)\n",
            "y3_outlier = y3.copy()\n",
            "outlier_indices = [10, 25, 40, 55, 70]\n",
            "y3_outlier[outlier_indices] = 100.0\n",
            "\n",
            "# 1. Train LinearRegression (OLS - hàm mất mát MSE)\n",
            "ols3 = LinearRegression()\n",
            "ols3.fit(x3.reshape(-1, 1), y3_outlier)\n",
            "\n",
            "# 2. Train HuberRegressor (robust loss)\n",
            "huber3 = HuberRegressor()\n",
            "huber3.fit(x3.reshape(-1, 1), y3_outlier)\n",
            "\n",
            "print(f\"Ground Truth:      w = 3.0000,  b = 5.0000\")\n",
            "print(f\"Linear Regression: w = {ols3.coef_[0]:.4f},  b = {ols3.intercept_:.4f}\")\n",
            "print(f\"HuberRegressor:    w = {huber3.coef_[0]:.4f},  b = {huber3.intercept_:.4f}\")\n",
            "\n",
            "diff_ols = np.sqrt((ols3.coef_[0] - 3)**2 + (ols3.intercept_ - 5)**2)\n",
            "diff_huber = np.sqrt((huber3.coef_[0] - 3)**2 + (huber3.intercept_ - 5)**2)\n",
            "print(f\"\\nĐộ lệch tham số so với nghiệm thật (3, 5):\")\n",
            "print(f\"  - Linear Regression lệch: {diff_ols:.4f}\")\n",
            "print(f\"  - HuberRegressor lệch:    {diff_huber:.4f}\")\n",
            "\n",
            "# Vẽ biểu đồ so sánh\n",
            "plt.figure(figsize=(9, 4.5))\n",
            "normal_idx = [i for i in range(N3) if i not in outlier_indices]\n",
            "plt.scatter(x3[normal_idx], y3_outlier[normal_idx], alpha=0.6, color='steelblue', label='Dữ liệu thường (95 điểm)')\n",
            "plt.scatter(x3[outlier_indices], y3_outlier[outlier_indices], color='crimson', s=80, edgecolors='black', label='5 Outliers cực đoan (y = 100)')\n",
            "\n",
            "x3_plot = np.linspace(0, 10, 200).reshape(-1, 1)\n",
            "plt.plot(x3_plot, 3 * x3_plot + 5, 'g--', lw=2, label='True line: y = 3x + 5')\n",
            "plt.plot(x3_plot, ols3.predict(x3_plot), 'r-', lw=2, label=f'OLS (bị méo): w={ols3.coef_[0]:.2f}, b={ols3.intercept_:.2f}')\n",
            "plt.plot(x3_plot, huber3.predict(x3_plot), 'b-.', lw=2.5, label=f'Huber (vững): w={huber3.coef_[0]:.2f}, b={huber3.intercept_:.2f}')\n",
            "\n",
            "plt.xlabel('x'); plt.ylabel('y')\n",
            "plt.title('Bài tập 3: Khả năng chống chịu Outlier của HuberRegressor vs LinearRegression')\n",
            "plt.legend(); plt.grid(alpha=0.3)\n",
            "plt.show()\n"
        ]

    # 5. Cập nhật cell Bài 4 (lr-bt4-code)
    elif cid == "lr-bt4-code":
        cell["source"] = [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.linear_model import LinearRegression, Ridge, Lasso\n",
            "\n",
            "np.random.seed(42)\n",
            "N4, D4 = 100, 20\n",
            "# Sinh dữ liệu 100 mẫu, 20 đặc trưng\n",
            "X4 = np.random.randn(N4, D4)\n",
            "\n",
            "# Chỉ 5 đặc trưng đầu tiên thật sự liên quan, 15 đặc trưng sau là nhiễu\n",
            "true_coef4 = np.zeros(D4)\n",
            "true_coef4[:5] = [4.5, -3.2, 5.0, -2.8, 3.8]\n",
            "y4 = X4 @ true_coef4 + np.random.randn(N4) * 0.5\n",
            "\n",
            "# Chuẩn hóa đặc trưng\n",
            "scaler4 = StandardScaler()\n",
            "X4_s = scaler4.fit_transform(X4)\n",
            "\n",
            "# 1. Huấn luyện 3 mô hình\n",
            "lr4 = LinearRegression().fit(X4_s, y4)\n",
            "ridge4 = Ridge(alpha=1.0).fit(X4_s, y4)\n",
            "lasso4 = Lasso(alpha=0.1).fit(X4_s, y4)\n",
            "\n",
            "# 2. Đếm số hệ số khác 0 (ngưỡng 1e-6)\n",
            "nz_lr4 = np.sum(np.abs(lr4.coef_) > 1e-6)\n",
            "nz_ridge4 = np.sum(np.abs(ridge4.coef_) > 1e-6)\n",
            "nz_lasso4 = np.sum(np.abs(lasso4.coef_) > 1e-6)\n",
            "\n",
            "print(f\"Số feature thật sự có ý nghĩa: 5 / 20\")\n",
            "print(f\"1. Linear Regression: {nz_lr4}/20 coef khác 0\")\n",
            "print(f\"2. Ridge (alpha=1.0): {nz_ridge4}/20 coef khác 0\")\n",
            "print(f\"3. Lasso (alpha=0.1): {nz_lasso4}/20 coef khác 0\")\n",
            "\n",
            "# 3. Kiểm tra Lasso có phát hiện 5 feature thật không\n",
            "selected_features = np.where(np.abs(lasso4.coef_) > 1e-6)[0]\n",
            "print(f\"\\nChỉ số các đặc trưng Lasso chọn (coef > 1e-6): {selected_features}\")\n",
            "print(f\"Chỉ số 5 đặc trưng thật ban đầu:              [0, 1, 2, 3, 4]\")\n",
            "if np.array_equal(selected_features, np.arange(5)):\n",
            "    print(\"=> Lasso đã phát hiện CHÍNH XÁC HOÀN TOÀN 5 feature thật và triệt tiêu 15 feature thừa về 0!\")\n",
            "\n",
            "# Vẽ biểu đồ so sánh trọng số của 3 mô hình\n",
            "plt.figure(figsize=(11, 4.5))\n",
            "idx = np.arange(D4)\n",
            "w_bar = 0.2\n",
            "plt.bar(idx - 1.5*w_bar, true_coef4, w_bar, label='Ground Truth', color='black', alpha=0.8)\n",
            "plt.bar(idx - 0.5*w_bar, lr4.coef_, w_bar, label='LinearRegression', color='crimson', alpha=0.7)\n",
            "plt.bar(idx + 0.5*w_bar, ridge4.coef_, w_bar, label='Ridge (α=1.0)', color='royalblue', alpha=0.7)\n",
            "plt.bar(idx + 1.5*w_bar, lasso4.coef_, w_bar, label='Lasso (α=0.1)', color='forestgreen', alpha=0.85)\n",
            "plt.axvline(4.5, color='purple', linestyle=':', label='Ranh giới 5 feature thật')\n",
            "plt.xticks(idx, [f'X{i}' for i in range(D4)])\n",
            "plt.xlabel('Features')\n",
            "plt.ylabel('Hệ số (Weight)')\n",
            "plt.title('Bài tập 4: So sánh trọng số học được giữa OLS, Ridge và Lasso')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.tight_layout()\n",
            "plt.show()\n"
        ]

    # 6. Cập nhật cell Bài 5 (lr-bt5-code)
    elif cid == "lr-bt5-code":
        cell["source"] = [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.preprocessing import StandardScaler, PolynomialFeatures\n",
            "from sklearn.linear_model import LinearRegression\n",
            "from sklearn.pipeline import make_pipeline\n",
            "from sklearn.metrics import mean_squared_error\n",
            "\n",
            "# Sử dụng lại tập dữ liệu sin(x) từ phần Thực hành cuối\n",
            "np.random.seed(0)\n",
            "x_train_5 = np.sort(np.random.uniform(0, 2*np.pi, 22))\n",
            "y_train_5 = np.sin(x_train_5) + np.random.randn(22) * 0.20\n",
            "\n",
            "x_test_5 = np.sort(np.random.uniform(0, 2*np.pi, 300))\n",
            "y_test_5 = np.sin(x_test_5) + np.random.randn(300) * 0.20\n",
            "\n",
            "degrees = range(1, 18)\n",
            "train_rmses = []\n",
            "test_rmses = []\n",
            "\n",
            "for d in degrees:\n",
            "    pipe = make_pipeline(PolynomialFeatures(d), StandardScaler(), LinearRegression())\n",
            "    pipe.fit(x_train_5.reshape(-1, 1), y_train_5)\n",
            "    \n",
            "    pred_tr = pipe.predict(x_train_5.reshape(-1, 1))\n",
            "    pred_te = pipe.predict(x_test_5.reshape(-1, 1))\n",
            "    \n",
            "    train_rmses.append(np.sqrt(mean_squared_error(y_train_5, pred_tr)))\n",
            "    test_rmses.append(np.sqrt(mean_squared_error(y_test_5, pred_te)))\n",
            "\n",
            "best_d_idx = np.argmin(test_rmses)\n",
            "best_d = list(degrees)[best_d_idx]\n",
            "print(f\"Đáy của đường test RMSE đạt tại: degree = {best_d}\")\n",
            "print(f\"  - Train RMSE tại degree {best_d}: {train_rmses[best_d_idx]:.4f}\")\n",
            "print(f\"  - Test RMSE tại degree {best_d} : {test_rmses[best_d_idx]:.4f}\")\n",
            "\n",
            "# Vẽ đồ thị so sánh RMSE theo degree (thang log)\n",
            "plt.figure(figsize=(9, 4.5))\n",
            "plt.plot(degrees, train_rmses, 'b-o', lw=2, label='Train RMSE (22 mẫu)')\n",
            "plt.plot(degrees, test_rmses, 'r-s', lw=2, label='Test RMSE (300 mẫu)')\n",
            "plt.axvline(best_d, color='green', linestyle='--', label=f'Đáy Test RMSE (degree = {best_d})')\n",
            "plt.yscale('log')\n",
            "plt.xticks(degrees)\n",
            "plt.xlabel('Polynomial Degree (Bậc đa thức)')\n",
            "plt.ylabel('RMSE (thang đo log)')\n",
            "plt.title('Bài tập 5: Đường cong Bias-Variance Tradeoff theo bậc đa thức')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.show()\n"
        ]

    # 7. Cập nhật cell Bài 5 mở rộng (lr-bt5-extra-code)
    elif cid == "lr-bt5-extra-code":
        cell["source"] = [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.preprocessing import StandardScaler, PolynomialFeatures\n",
            "from sklearn.linear_model import LinearRegression\n",
            "from sklearn.pipeline import make_pipeline\n",
            "from sklearn.metrics import mean_squared_error\n",
            "\n",
            "# Sinh dữ liệu train lớn: N = 500 điểm\n",
            "np.random.seed(0)\n",
            "x_train_500 = np.sort(np.random.uniform(0, 2*np.pi, 500))\n",
            "y_train_500 = np.sin(x_train_500) + np.random.randn(500) * 0.20\n",
            "\n",
            "train_rmses_500 = []\n",
            "test_rmses_500 = []\n",
            "\n",
            "for d in degrees:\n",
            "    pipe = make_pipeline(PolynomialFeatures(d), StandardScaler(), LinearRegression())\n",
            "    pipe.fit(x_train_500.reshape(-1, 1), y_train_500)\n",
            "    \n",
            "    pred_tr = pipe.predict(x_train_500.reshape(-1, 1))\n",
            "    pred_te = pipe.predict(x_test_5.reshape(-1, 1))\n",
            "    \n",
            "    train_rmses_500.append(np.sqrt(mean_squared_error(y_train_500, pred_tr)))\n",
            "    test_rmses_500.append(np.sqrt(mean_squared_error(y_test_5, pred_te)))\n",
            "\n",
            "# Vẽ so sánh 2 trường hợp: 22 mẫu vs 500 mẫu\n",
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4.5))\n",
            "\n",
            "ax1.plot(degrees, train_rmses, 'b-o', label='Train RMSE (22 mẫu)')\n",
            "ax1.plot(degrees, test_rmses, 'r-s', label='Test RMSE (300 mẫu)')\n",
            "ax1.set_yscale('log'); ax1.set_xticks(degrees)\n",
            "ax1.set_xlabel('Degree'); ax1.set_ylabel('RMSE (log scale)')\n",
            "ax1.set_title('N = 22 mẫu: Overfitting bùng nổ ở bậc cao')\n",
            "ax1.legend(); ax1.grid(alpha=0.3)\n",
            "\n",
            "ax2.plot(degrees, train_rmses_500, 'b-o', label='Train RMSE (500 mẫu)')\n",
            "ax2.plot(degrees, test_rmses_500, 'r-s', label='Test RMSE (300 mẫu)')\n",
            "ax2.set_yscale('log'); ax2.set_xticks(degrees)\n",
            "ax2.set_xlabel('Degree'); ax2.set_ylabel('RMSE (log scale)')\n",
            "ax2.set_title('N = 500 mẫu: Không còn hiện tượng Overfitting!')\n",
            "ax2.legend(); ax2.grid(alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "print(f\"Khi N = 500 mẫu:\")\n",
            "print(f\"  - Degree 3:  Test RMSE = {test_rmses_500[2]:.4f}\")\n",
            "print(f\"  - Degree 17: Test RMSE = {test_rmses_500[-1]:.4f}\")\n"
        ]

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Updated notebook imports successfully!")
